Verbs = function(){
	var words = [
	"trounced",
	"smote",
	"clowned upon",
	"hornswoggled",
	"bladesed upon",
	"squirted",
	"embarassed",
	"destroyed",
	"beat",
	"beat down",
	"drubbed",
	"smashed",
	"licked",
	"lambasted",
	"thrashed",
	"shellacked",
	"smeared",
	"whipped",
	"blasted",
	"battered",
	"mangled",
	"socked",
	"slammed",
	"tallywhacked",
	"bashed",
	"KOd",
	"whomped",
	"wiped out",
	"put away",
	"took down",
	"wallopped",
	"hosed",
	"clobbered",
	"dominated",
	"delivered a beating upon",
	"smote",
	"destroyed",
	"crushed",
	"crunked",
	"corked",
	"spanked",
	"folded",
	"dunked",
	"groin-kicked",
	"pantsed",
	"throttled",
	"took the piss out of",
	"killed",
	"disemboweled",
	"defenestrated",
	"defecated upon",
	"pooped on",
	"popped",
	"schmeared",
	"booted",
	"bashed",
	"berserked",
	"squashed",
	"took down",
	"squished",
	"beat",
	"pummeled",
	"hurt the feelings of ",
	"devastated",
	"depressed",
	"hurt",
	"emotionally crippled",
	"punched the mug of",
	"cold cocked",
	"sucker punched",
	"clobbered",
	"ko’d",
	"jabbed",
	"hospitalized",
	"put out to pasture",
	"pasteurized",
	"shook",
	"neutralized",
	"spayed and/or neutered",
	"shellacked",
	"terminated",
	"tore to shreds",
	"ripped a new one",
	"shredded",
	"corralled ",
	"cro-barred",
	"housed",
	"roundhouse kicked",
	"hosed",
	"cracked",
	"smacked",
	"smoked",
	"beheaded",
	"vanquished",
	"annihilated",
	"crushed",
	"eliminated",
	"got biblical on",
	"tyrranized ",
	"brought great vengeance upon",
	"poisoned ",
	"reigned supreme against",
	"subdued",
	"put to sleep",
	"red wedding’d",
	"crapped all over",
	"thwacked",
	"thumped",
	"drubbed",
	"pucked",
	"punked",
	"bullied",
	"checked",
	"rocked",
	"cross-checked",
	"deked",
	"dropped",
	"dusted",
	"froze",
	"gooned",
	"grinded",
	"hacked",
	"stuck",
	"spiked",
	"iced",
	"lit up",
	"bum-rushed",
	"peppered",
	"assaulted",
	"powered past",
	"crunked",
	"stopped",
	"roughed up",
	"shafted",
	"shutdown",
	"slashed",
	"speared",
	"slapped",
	"sniped",
	"bulldozed",
	"tagged",
	"vaulted past",
	"zamboni’d",
	"cleaned the clock of",
	"face-punched",
	"stuck it to",];
	return words[Math.floor(Math.random()*words.length)];
};